server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit #  消息组件类型
          environment: # 设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: #这是一个通道的名称
          destination: studyExchange # 表示使用exchange名称定义
          content-type: application/json #  设置消息类型，本次为json，文本则设置为“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: mygroup1
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
    instance:
      lease-renewal-interval-in-seconds: 2 # 设置心跳时间间隔默认是 30s
      lease-expiration-duration-in-seconds: 5
      instance-id: receive-8803.com # 在信息列表这是显示主机信息
      preper-ip-address: true # 访问路径变为ip地址